### ISSUE TITLE
Attacking either Automaton, Drake, Kobold or Kobold Warrior crashes the game

### ISSUE THREAD

**Issue by ZiLenTz** [kyber-6/mythicmobs#32]
### Describe the bug

- Only apply to melee attacking with weapon or bare hands while ranged weapons work fine.
- Only apply to Automaton, Drake, Kobold and Kobold Warrior while Chupacabra and Sporeling are fine.
- Immediately after one of these 4 entities are hit, the game will crash.
- However, everything works when other mobs fight with these 4 mobs.

### Reproduction steps

1. Enter the game and create world
2. Find either Automaton, Drake, Kobold or Kobold Warrior (or spawn them with egg)
3. Melee against them with or without weapon
4. Result in game crash immediately

### Logs & crash-reports

Automaton: https://mclo.gs/YVYD99O
Drake: https://mclo.gs/2GlvTe1
Kobold Warrior: https://mclo.gs/LozOKeE
Kobold: https://mclo.gs/VA72c3C

### Mod version

1.4.5

### Minecraft version

1.20.1

**Comment by agent14bricks** [comment]
Using the mod "Happiness (is a) Warm Gun" (HWG), I still get the crash even with their ranged solutions (guns).
Crash logs are the exact same in the error portion.
Using vanilla bow and arrow too causes the same issue, not just melee. The only time I did notice it didn't crash was when I missed with a modded bow, and it did explosion damage instead of direct damage.

**Comment by outercloudstudio** [comment]
This issue occurs when the universalAnger game rule is enabled.

**Comment by thrasos-dev** [comment]
Please test if the issue persists in the rewrite.
